[tool.poetry]
name = "xmlrpc-brute-forcer"
version = "0.1.0"
description = ""
authors = ["Talha Eryasar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"
rich = "^13.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
